/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <I2CS.h>
#include <I2CS_I2C.h>
#include <I2CS_PINS.h>
#include <I2CS_I2C_PVT.h>
#include <I2CS_PVT.h>
#include <PWM.h>
#include <Clock.h>
#include <STEP.h>
#include <STEP_aliases.h>
#include <Control_Reg.h>
#include <DIR.h>
#include <DIR_aliases.h>
#include <nEN.h>
#include <nEN_aliases.h>
#include <Counter_1.h>
#include <hall.h>
#include <hall_aliases.h>
#include <nSLEEP.h>
#include <nSLEEP_aliases.h>
#include <cap1.h>
#include <cap1_aliases.h>
#include <cap2.h>
#include <cap2_aliases.h>
#include <M0.h>
#include <M0_aliases.h>
#include <M1.h>
#include <M1_aliases.h>
#include <EEPROM.h>
#include <I2CS_sda.h>
#include <I2CS_sda_aliases.h>
#include <I2CS_scl.h>
#include <I2CS_scl_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

